System.config({
  defaultJSExtensions: true,
  transpiler: "none",
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "kendo.*": "vendors/js/kendo.*.js",
    "kendo-ui/*": "vendors/*"
  },
  meta: {
    "bootstrap": {
      "deps": [
        "jquery"
      ]
    }
  },
  map: {
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.2.0.1",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.2.0.1",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.2.0.1",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.2.0.1",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.2.0.1",
    "aurelia-kendoui-bridge": "npm:aurelia-kendoui-bridge@0.11.2",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.2.0.2",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.2.0.1",
    "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.3.0.1",
    "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.2.0.1",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.2.0.1",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.2.0.2",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.3.0.4",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.2.0.3",
    "bootstrap": "github:twbs/bootstrap@3.3.6",
    "css": "github:systemjs/plugin-css@0.1.23",
    "fetch": "github:github/fetch@1.0.0",
    "font-awesome": "npm:font-awesome@4.6.3",
    "jquery": "npm:jquery@2.2.4",
    "text": "github:systemjs/plugin-text@0.0.3",
    "github:twbs/bootstrap@3.3.6": {
      "jquery": "npm:jquery@2.2.4"
    },
    "npm:aurelia-animator-css@1.0.0-beta.2.0.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.2.0.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.3.0.6"
    },
    "npm:aurelia-binding@1.0.0-beta.2.0.7": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.2.0.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.2.0.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.2.0.1"
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.2.0.1": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.2.0.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.2.0.1",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.2.0.1",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.2.0.1",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.2.0.2",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.2.0.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.3.0.1",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.2.0.1",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.2.0.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.3.0.6",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.2.0.2",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.3.0.4",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.2.0.3"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.2.1.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.2.0.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.2.0.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.2.0.1"
    },
    "npm:aurelia-framework@1.0.0-beta.2.0.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.2.0.7",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.2.1.1",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.2.0.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.2.0.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.2.0.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.2.0.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.2.0.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.3.0.6"
    },
    "npm:aurelia-history-browser@1.0.0-beta.2.0.1": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.2.0.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0"
    },
    "npm:aurelia-kendoui-bridge@0.11.2": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.2.0.7",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.2.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.2.0.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.2.0.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.2.0.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.3.0.6",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.3.0.4"
    },
    "npm:aurelia-loader-default@1.0.0-beta.2.0.2": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.2.0.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.2.0.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0"
    },
    "npm:aurelia-loader@1.0.0-beta.2.0.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.2.0.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.2.0.1"
    },
    "npm:aurelia-logging-console@1.0.0-beta.2.0.1": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.2.0.1"
    },
    "npm:aurelia-metadata@1.0.0-beta.2.0.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.3.0.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0"
    },
    "npm:aurelia-polyfills@1.0.0-beta.2.0.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.2.0.1": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.2.0.1"
    },
    "npm:aurelia-router@1.0.0-beta.2.0.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.2.1.1",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.2.0.1",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.2.0.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.2.0.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.2.0.1",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.2.0.1"
    },
    "npm:aurelia-task-queue@1.0.0-beta.2.0.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.2.0.2": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.2.0.7",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.2.0.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.3.0.6"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.3.0.4": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.2.0.7",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.2.1.1",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.2.0.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.2.0.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.2.0.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.2.0.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.2.0.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.3.0.6"
    },
    "npm:aurelia-templating-router@1.0.0-beta.2.0.3": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.2.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.2.0.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.2.0.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.2.0.1",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.2.0.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.3.0.6"
    },
    "npm:aurelia-templating@1.0.0-beta.3.0.6": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.2.0.7",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.2.1.1",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.2.0.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.2.0.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.2.0.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.2.0.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.2.0.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.2.0.1"
    },
    "npm:font-awesome@4.6.3": {
      "css": "github:systemjs/plugin-css@0.1.23"
    }
  },
  bundles: {
    "app-build.js": [
      "app.html!github:systemjs/plugin-text@0.0.3.js",
      "app.js",
      "blur-image.js",
      "child-router.html!github:systemjs/plugin-text@0.0.3.js",
      "child-router.js",
      "main.js",
      "nav-bar.html!github:systemjs/plugin-text@0.0.3.js",
      "users.html!github:systemjs/plugin-text@0.0.3.js",
      "users.js",
      "welcome.html!github:systemjs/plugin-text@0.0.3.js",
      "welcome.js"
    ],
    "aurelia.js": [
      "github:github/fetch@1.0.0.js",
      "github:github/fetch@1.0.0/fetch.js",
      "github:twbs/bootstrap@3.3.6.js",
      "github:twbs/bootstrap@3.3.6/css/bootstrap.css!github:systemjs/plugin-text@0.0.3.js",
      "github:twbs/bootstrap@3.3.6/js/bootstrap.js",
      "npm:aurelia-animator-css@1.0.0-beta.2.0.1.js",
      "npm:aurelia-animator-css@1.0.0-beta.2.0.1/aurelia-animator-css.js",
      "npm:aurelia-binding@1.0.0-beta.2.0.7.js",
      "npm:aurelia-binding@1.0.0-beta.2.0.7/aurelia-binding.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.2.0.1.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.2.0.1/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.2.1.1.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.2.1.1/aurelia-dependency-injection.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.2.0.1.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.2.0.1/aurelia-event-aggregator.js",
      "npm:aurelia-fetch-client@1.0.0-beta.2.0.1.js",
      "npm:aurelia-fetch-client@1.0.0-beta.2.0.1/aurelia-fetch-client.js",
      "npm:aurelia-framework@1.0.0-beta.2.0.1.js",
      "npm:aurelia-framework@1.0.0-beta.2.0.1/aurelia-framework.js",
      "npm:aurelia-history-browser@1.0.0-beta.2.0.1.js",
      "npm:aurelia-history-browser@1.0.0-beta.2.0.1/aurelia-history-browser.js",
      "npm:aurelia-history@1.0.0-beta.2.0.1.js",
      "npm:aurelia-history@1.0.0-beta.2.0.1/aurelia-history.js",
      "npm:aurelia-loader-default@1.0.0-beta.2.0.2.js",
      "npm:aurelia-loader-default@1.0.0-beta.2.0.2/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.0-beta.2.0.1.js",
      "npm:aurelia-loader@1.0.0-beta.2.0.1/aurelia-loader.js",
      "npm:aurelia-logging-console@1.0.0-beta.2.0.1.js",
      "npm:aurelia-logging-console@1.0.0-beta.2.0.1/aurelia-logging-console.js",
      "npm:aurelia-logging@1.0.0-beta.2.0.1.js",
      "npm:aurelia-logging@1.0.0-beta.2.0.1/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.0-beta.2.0.1.js",
      "npm:aurelia-metadata@1.0.0-beta.2.0.1/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.0.0-beta.3.0.1.js",
      "npm:aurelia-pal-browser@1.0.0-beta.3.0.1/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.0.0-beta.2.0.0.js",
      "npm:aurelia-pal@1.0.0-beta.2.0.0/aurelia-pal.js",
      "npm:aurelia-path@1.0.0-beta.2.0.1.js",
      "npm:aurelia-path@1.0.0-beta.2.0.1/aurelia-path.js",
      "npm:aurelia-polyfills@1.0.0-beta.2.0.1.js",
      "npm:aurelia-polyfills@1.0.0-beta.2.0.1/aurelia-polyfills.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.2.0.1.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.2.0.1/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.0.0-beta.2.0.1.js",
      "npm:aurelia-router@1.0.0-beta.2.0.1/aurelia-router.js",
      "npm:aurelia-task-queue@1.0.0-beta.2.0.1.js",
      "npm:aurelia-task-queue@1.0.0-beta.2.0.1/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.0.0-beta.2.0.2.js",
      "npm:aurelia-templating-binding@1.0.0-beta.2.0.2/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/abstract-repeater.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/analyze-view-factory.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/array-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/aurelia-hide-style.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/aurelia-templating-resources.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/binding-mode-behaviors.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/binding-signaler.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/compose.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/css-resource.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/debounce-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/dynamic-element.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/focus.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/hide.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/html-resource-plugin.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/html-sanitizer.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/if.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/map-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/null-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/number-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/repeat-strategy-locator.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/repeat-utilities.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/repeat.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/replaceable.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/sanitize-html.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/set-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/show.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/signal-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/throttle-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/update-trigger-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.3.0.4/with.js",
      "npm:aurelia-templating-router@1.0.0-beta.2.0.3.js",
      "npm:aurelia-templating-router@1.0.0-beta.2.0.3/aurelia-templating-router.js",
      "npm:aurelia-templating-router@1.0.0-beta.2.0.3/route-href.js",
      "npm:aurelia-templating-router@1.0.0-beta.2.0.3/route-loader.js",
      "npm:aurelia-templating-router@1.0.0-beta.2.0.3/router-view.js",
      "npm:aurelia-templating@1.0.0-beta.3.0.6.js",
      "npm:aurelia-templating@1.0.0-beta.3.0.6/aurelia-templating.js",
      "npm:jquery@2.2.4.js",
      "npm:jquery@2.2.4/dist/jquery.js"
    ],
    "plugins.js": [
      "npm:aurelia-kendoui-bridge@0.11.2.js",
      "npm:aurelia-kendoui-bridge@0.11.2/autocomplete/autocomplete.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/autocomplete/autocomplete.js",
      "npm:aurelia-kendoui-bridge@0.11.2/barcode/barcode.js",
      "npm:aurelia-kendoui-bridge@0.11.2/button/button.js",
      "npm:aurelia-kendoui-bridge@0.11.2/buttongroup/buttongroup.js",
      "npm:aurelia-kendoui-bridge@0.11.2/calendar/calendar.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/calendar/calendar.js",
      "npm:aurelia-kendoui-bridge@0.11.2/chart/chart.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/chart/chart.js",
      "npm:aurelia-kendoui-bridge@0.11.2/chart/sparkline.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/chart/sparkline.js",
      "npm:aurelia-kendoui-bridge@0.11.2/chart/stock.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/chart/stock.js",
      "npm:aurelia-kendoui-bridge@0.11.2/chart/treemap.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/chart/treemap.js",
      "npm:aurelia-kendoui-bridge@0.11.2/colorpalette/colorpalette.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/colorpalette/colorpalette.js",
      "npm:aurelia-kendoui-bridge@0.11.2/colorpicker/colorpicker.js",
      "npm:aurelia-kendoui-bridge@0.11.2/combobox/combobox.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/combobox/combobox.js",
      "npm:aurelia-kendoui-bridge@0.11.2/common/bindables.js",
      "npm:aurelia-kendoui-bridge@0.11.2/common/constants.js",
      "npm:aurelia-kendoui-bridge@0.11.2/common/control-properties.js",
      "npm:aurelia-kendoui-bridge@0.11.2/common/decorators.js",
      "npm:aurelia-kendoui-bridge@0.11.2/common/notify-binding-behavior.js",
      "npm:aurelia-kendoui-bridge@0.11.2/common/options-builder.js",
      "npm:aurelia-kendoui-bridge@0.11.2/common/template-compiler.js",
      "npm:aurelia-kendoui-bridge@0.11.2/common/template-gatherer.js",
      "npm:aurelia-kendoui-bridge@0.11.2/common/template.js",
      "npm:aurelia-kendoui-bridge@0.11.2/common/util.js",
      "npm:aurelia-kendoui-bridge@0.11.2/common/widget-base.js",
      "npm:aurelia-kendoui-bridge@0.11.2/config-builder.js",
      "npm:aurelia-kendoui-bridge@0.11.2/contextmenu/contextmenu.js",
      "npm:aurelia-kendoui-bridge@0.11.2/datepicker/datepicker.js",
      "npm:aurelia-kendoui-bridge@0.11.2/datetimepicker/datetimepicker.js",
      "npm:aurelia-kendoui-bridge@0.11.2/diagram/diagram.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/diagram/diagram.js",
      "npm:aurelia-kendoui-bridge@0.11.2/draggable/draggable.js",
      "npm:aurelia-kendoui-bridge@0.11.2/drop-target/drop-target-area.js",
      "npm:aurelia-kendoui-bridge@0.11.2/drop-target/drop-target.js",
      "npm:aurelia-kendoui-bridge@0.11.2/dropdownlist/dropdownlist.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/dropdownlist/dropdownlist.js",
      "npm:aurelia-kendoui-bridge@0.11.2/editor/editor.js",
      "npm:aurelia-kendoui-bridge@0.11.2/flatcolorpicker/flatcolorpicker.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/flatcolorpicker/flatcolorpicker.js",
      "npm:aurelia-kendoui-bridge@0.11.2/gantt/gantt-col.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/gantt/gantt-col.js",
      "npm:aurelia-kendoui-bridge@0.11.2/gantt/gantt.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/gantt/gantt.js",
      "npm:aurelia-kendoui-bridge@0.11.2/gauges/linear-gauge.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/gauges/linear-gauge.js",
      "npm:aurelia-kendoui-bridge@0.11.2/gauges/radial-gauge.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/gauges/radial-gauge.js",
      "npm:aurelia-kendoui-bridge@0.11.2/grid/col.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/grid/col.js",
      "npm:aurelia-kendoui-bridge@0.11.2/grid/grid-toolbar.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/grid/grid-toolbar.js",
      "npm:aurelia-kendoui-bridge@0.11.2/grid/grid.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/grid/grid.js",
      "npm:aurelia-kendoui-bridge@0.11.2/index.js",
      "npm:aurelia-kendoui-bridge@0.11.2/listview/listview.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/listview/listview.js",
      "npm:aurelia-kendoui-bridge@0.11.2/map/map.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/map/map.js",
      "npm:aurelia-kendoui-bridge@0.11.2/maskedtextbox/maskedtextbox.js",
      "npm:aurelia-kendoui-bridge@0.11.2/menu/menu.js",
      "npm:aurelia-kendoui-bridge@0.11.2/multiselect/multiselect.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/multiselect/multiselect.js",
      "npm:aurelia-kendoui-bridge@0.11.2/notification/notification-template.js",
      "npm:aurelia-kendoui-bridge@0.11.2/notification/notification.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/notification/notification.js",
      "npm:aurelia-kendoui-bridge@0.11.2/numerictextbox/numerictextbox.js",
      "npm:aurelia-kendoui-bridge@0.11.2/panelbar/panelbar.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/panelbar/panelbar.js",
      "npm:aurelia-kendoui-bridge@0.11.2/pdf/pdf.js",
      "npm:aurelia-kendoui-bridge@0.11.2/pivotgrid/pivotconfigurator.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/pivotgrid/pivotconfigurator.js",
      "npm:aurelia-kendoui-bridge@0.11.2/pivotgrid/pivotgrid.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/pivotgrid/pivotgrid.js",
      "npm:aurelia-kendoui-bridge@0.11.2/progressbar/progressbar.js",
      "npm:aurelia-kendoui-bridge@0.11.2/qrcode/qrcode.js",
      "npm:aurelia-kendoui-bridge@0.11.2/rangeslider/rangeslider.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/rangeslider/rangeslider.js",
      "npm:aurelia-kendoui-bridge@0.11.2/responsivepanel/responsivepanel.js",
      "npm:aurelia-kendoui-bridge@0.11.2/scheduler/scheduler.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/scheduler/scheduler.js",
      "npm:aurelia-kendoui-bridge@0.11.2/scrollview/scrollview.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/scrollview/scrollview.js",
      "npm:aurelia-kendoui-bridge@0.11.2/slider/slider.js",
      "npm:aurelia-kendoui-bridge@0.11.2/sortable/sortable.js",
      "npm:aurelia-kendoui-bridge@0.11.2/splitter/splitter.js",
      "npm:aurelia-kendoui-bridge@0.11.2/spreadsheet/spreadsheet.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/spreadsheet/spreadsheet.js",
      "npm:aurelia-kendoui-bridge@0.11.2/switch/switch.js",
      "npm:aurelia-kendoui-bridge@0.11.2/tabstrip/tabstrip.js",
      "npm:aurelia-kendoui-bridge@0.11.2/timepicker/timepicker.js",
      "npm:aurelia-kendoui-bridge@0.11.2/toolbar/toolbar-item-button.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/toolbar/toolbar-item-button.js",
      "npm:aurelia-kendoui-bridge@0.11.2/toolbar/toolbar-item.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/toolbar/toolbar-item.js",
      "npm:aurelia-kendoui-bridge@0.11.2/toolbar/toolbar.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/toolbar/toolbar.js",
      "npm:aurelia-kendoui-bridge@0.11.2/tooltip/tooltip.js",
      "npm:aurelia-kendoui-bridge@0.11.2/treelist/tree-col.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/treelist/tree-col.js",
      "npm:aurelia-kendoui-bridge@0.11.2/treelist/treelist.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/treelist/treelist.js",
      "npm:aurelia-kendoui-bridge@0.11.2/treeview/treeview.js",
      "npm:aurelia-kendoui-bridge@0.11.2/upload/upload.html!github:systemjs/plugin-text@0.0.3.js",
      "npm:aurelia-kendoui-bridge@0.11.2/upload/upload.js",
      "npm:aurelia-kendoui-bridge@0.11.2/validator/validator.js",
      "npm:aurelia-kendoui-bridge@0.11.2/valueconverters/valueconverters.js",
      "npm:aurelia-kendoui-bridge@0.11.2/window/window.js"
    ],
    "kendo-build-10902f2890.js": [
      "kendo-ui/js/jszip.min.js",
      "kendo-ui/js/pako_deflate.min.js",
      "kendo.autocomplete.min",
      "kendo.binder.min",
      "kendo.button.min",
      "kendo.calendar.min",
      "kendo.color.min",
      "kendo.colorpicker.min",
      "kendo.columnmenu.min",
      "kendo.columnsorter.min",
      "kendo.combobox.min",
      "kendo.core.min",
      "kendo.data.min",
      "kendo.data.odata.min",
      "kendo.data.signalr.min",
      "kendo.data.xml.min",
      "kendo.dataviz.barcode.min",
      "kendo.dataviz.chart.funnel.min",
      "kendo.dataviz.chart.min",
      "kendo.dataviz.chart.polar.min",
      "kendo.dataviz.core.min",
      "kendo.dataviz.diagram.min",
      "kendo.dataviz.gauge.min",
      "kendo.dataviz.map.min",
      "kendo.dataviz.qrcode.min",
      "kendo.dataviz.sparkline.min",
      "kendo.dataviz.stock.min",
      "kendo.dataviz.themes.min",
      "kendo.dataviz.treemap.min",
      "kendo.datepicker.min",
      "kendo.datetimepicker.min",
      "kendo.dom.min",
      "kendo.draganddrop.min",
      "kendo.drawing.min",
      "kendo.dropdownlist.min",
      "kendo.editable.min",
      "kendo.editor.min",
      "kendo.excel.min",
      "kendo.filebrowser.min",
      "kendo.filtercell.min",
      "kendo.filtermenu.min",
      "kendo.fx.min",
      "kendo.gantt.list.min",
      "kendo.gantt.min",
      "kendo.gantt.timeline.min",
      "kendo.grid.min",
      "kendo.groupable.min",
      "kendo.imagebrowser.min",
      "kendo.list.min",
      "kendo.listview.min",
      "kendo.maskedtextbox.min",
      "kendo.menu.min",
      "kendo.mobile.actionsheet.min",
      "kendo.mobile.application.min",
      "kendo.mobile.button.min",
      "kendo.mobile.buttongroup.min",
      "kendo.mobile.collapsible.min",
      "kendo.mobile.drawer.min",
      "kendo.mobile.listview.min",
      "kendo.mobile.loader.min",
      "kendo.mobile.modalview.min",
      "kendo.mobile.navbar.min",
      "kendo.mobile.pane.min",
      "kendo.mobile.popover.min",
      "kendo.mobile.scroller.min",
      "kendo.mobile.scrollview.min",
      "kendo.mobile.shim.min",
      "kendo.mobile.splitview.min",
      "kendo.mobile.switch.min",
      "kendo.mobile.tabstrip.min",
      "kendo.mobile.view.min",
      "kendo.multiselect.min",
      "kendo.notification.min",
      "kendo.numerictextbox.min",
      "kendo.ooxml.min",
      "kendo.pager.min",
      "kendo.panelbar.min",
      "kendo.pdf.min",
      "kendo.pivot.configurator.min",
      "kendo.pivot.fieldmenu.min",
      "kendo.pivotgrid.min",
      "kendo.popup.min",
      "kendo.progressbar.min",
      "kendo.reorderable.min",
      "kendo.resizable.min",
      "kendo.responsivepanel.min",
      "kendo.router.min",
      "kendo.scheduler.agendaview.min",
      "kendo.scheduler.dayview.min",
      "kendo.scheduler.min",
      "kendo.scheduler.monthview.min",
      "kendo.scheduler.recurrence.min",
      "kendo.scheduler.timelineview.min",
      "kendo.scheduler.view.min",
      "kendo.selectable.min",
      "kendo.slider.min",
      "kendo.sortable.min",
      "kendo.splitter.min",
      "kendo.tabstrip.min",
      "kendo.timepicker.min",
      "kendo.timezones.min",
      "kendo.toolbar.min",
      "kendo.tooltip.min",
      "kendo.touch.min",
      "kendo.treelist.min",
      "kendo.treeview.draganddrop.min",
      "kendo.treeview.min",
      "kendo.upload.min",
      "kendo.userevents.min",
      "kendo.validator.min",
      "kendo.view.min",
      "kendo.virtuallist.min",
      "kendo.webcomponents.min",
      "kendo.window.min",
      "npm:jquery@2.2.4.js",
      "npm:jquery@2.2.4/dist/jquery.js"
    ]
  },
  depCache: {
    "blur-image.js": [
      "aurelia-framework"
    ],
    "main.js": [
      "bootstrap"
    ],
    "users.js": [
      "aurelia-framework",
      "aurelia-fetch-client",
      "fetch"
    ]
  }
});